# Generated by Django 3.2 on 2023-01-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Poun Sterling'), ('CHF', 'Swiss Franc'), ('AUD', 'Australlian dollar'), ('CAD', 'Canadian dollar'), ('NZD', 'New Zeland dollar')], max_length=3)),
            ],
        ),
    ]
