# Generated by Django 3.2 on 2023-01-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=1000, max_digits=10),
            preserve_default=False,
        ),
    ]
