# Generated by Django 3.2 on 2023-01-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_currency_type_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=1000, max_digits=10),
        ),
    ]
