# Generated by Django 3.2 on 2023-01-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_currency_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
